start:
		@make -j7 start1 start2 start3 start4 start5 start6 start7

start1:
		NODE_NAME=node-a HTTP_PORT=7947 CONFIG_URI=file://${PWD}/config.toml go run main.go

start2:
		NODE_NAME=node-b HTTP_PORT=7948 CONFIG_URI=file://${PWD}/config.toml go run main.go

start3:
		NODE_NAME=node-c HTTP_PORT=7949 CONFIG_URI=file://${PWD}/config.toml go run main.go

start4:
		NODE_NAME=node-d HTTP_PORT=7950 CONFIG_URI=file://${PWD}/config.toml go run main.go

start5:
		NODE_NAME=node-e HTTP_PORT=7951 CONFIG_URI=file://${PWD}/config.toml go run main.go

start6:
		NODE_NAME=node-f HTTP_PORT=7952 CONFIG_URI=file://${PWD}/config.toml go run main.go

start7:
		NODE_NAME=node-g HTTP_PORT=7953 CONFIG_URI=file://${PWD}/config.toml go run main.go