// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schedule/local/localpb/local.proto

/*
Package local is a generated protocol buffer package.

It is generated from these files:
	schedule/local/localpb/local.proto

It has these top-level messages:
	Partition
	Checkpoint
	Job
	JobOptions
	Event
*/
package local

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A Partition stores event keys within a specific time range
type Partition struct {
	From int64    `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To   int64    `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
	Keys []string `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
}

func (m *Partition) Reset()                    { *m = Partition{} }
func (m *Partition) String() string            { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()               {}
func (*Partition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Partition) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Partition) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Partition) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

// Checkpoint stores a time range. It is used to store the last load performed
// as a checkpoint to resume processing where it was left off.
type Checkpoint struct {
	Seq  uint64 `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	From int64  `protobuf:"varint,2,opt,name=from" json:"from,omitempty"`
	To   int64  `protobuf:"varint,3,opt,name=to" json:"to,omitempty"`
}

func (m *Checkpoint) Reset()                    { *m = Checkpoint{} }
func (m *Checkpoint) String() string            { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()               {}
func (*Checkpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Checkpoint) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Checkpoint) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Checkpoint) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

// A Job is a one-time task definition
type Job struct {
	Id      string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Target  string      `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	Due     int64       `protobuf:"varint,3,opt,name=due" json:"due,omitempty"`
	Data    []byte      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Options *JobOptions `protobuf:"bytes,15,opt,name=options" json:"options,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Job) GetDue() int64 {
	if m != nil {
		return m.Due
	}
	return 0
}

func (m *Job) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Job) GetOptions() *JobOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// JobOptions contains job execution options
type JobOptions struct {
	RetryLimit uint32 `protobuf:"varint,1,opt,name=retryLimit" json:"retryLimit,omitempty"`
	MinBackOff int64  `protobuf:"varint,2,opt,name=minBackOff" json:"minBackOff,omitempty"`
	MaxBackOff int64  `protobuf:"varint,3,opt,name=maxBackOff" json:"maxBackOff,omitempty"`
	AgeLimit   int64  `protobuf:"varint,4,opt,name=ageLimit" json:"ageLimit,omitempty"`
}

func (m *JobOptions) Reset()                    { *m = JobOptions{} }
func (m *JobOptions) String() string            { return proto.CompactTextString(m) }
func (*JobOptions) ProtoMessage()               {}
func (*JobOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JobOptions) GetRetryLimit() uint32 {
	if m != nil {
		return m.RetryLimit
	}
	return 0
}

func (m *JobOptions) GetMinBackOff() int64 {
	if m != nil {
		return m.MinBackOff
	}
	return 0
}

func (m *JobOptions) GetMaxBackOff() int64 {
	if m != nil {
		return m.MaxBackOff
	}
	return 0
}

func (m *JobOptions) GetAgeLimit() int64 {
	if m != nil {
		return m.AgeLimit
	}
	return 0
}

// An Event is an occurence of a job executed at a specific time.
// There is one event per job execution.
type Event struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Due     int64  `protobuf:"varint,2,opt,name=due" json:"due,omitempty"`
	Attempt uint32 `protobuf:"varint,3,opt,name=attempt" json:"attempt,omitempty"`
	Job     *Job   `protobuf:"bytes,15,opt,name=job" json:"job,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetDue() int64 {
	if m != nil {
		return m.Due
	}
	return 0
}

func (m *Event) GetAttempt() uint32 {
	if m != nil {
		return m.Attempt
	}
	return 0
}

func (m *Event) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func init() {
	proto.RegisterType((*Partition)(nil), "local.Partition")
	proto.RegisterType((*Checkpoint)(nil), "local.Checkpoint")
	proto.RegisterType((*Job)(nil), "local.Job")
	proto.RegisterType((*JobOptions)(nil), "local.JobOptions")
	proto.RegisterType((*Event)(nil), "local.Event")
}

func init() { proto.RegisterFile("schedule/local/localpb/local.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xcd, 0x6a, 0xb3, 0x40,
	0x14, 0x45, 0xc7, 0x24, 0x9f, 0xf7, 0x6b, 0xfa, 0x33, 0x8b, 0x22, 0xa5, 0x14, 0x71, 0x25, 0x14,
	0x52, 0x68, 0xdf, 0x20, 0xa1, 0x9b, 0x50, 0x48, 0x99, 0x37, 0x18, 0x75, 0x92, 0x4c, 0x13, 0x1d,
	0xab, 0x37, 0xa5, 0xd9, 0x75, 0xd9, 0xc7, 0x2e, 0x73, 0x1d, 0x93, 0x40, 0x36, 0x7a, 0x7e, 0x66,
	0xce, 0xf5, 0x5c, 0x84, 0xa4, 0xcd, 0xd7, 0xaa, 0xd8, 0x6d, 0xd5, 0xd3, 0xd6, 0xe4, 0x72, 0xdb,
	0x3d, 0xeb, 0xac, 0x7b, 0x4f, 0xea, 0xc6, 0xa0, 0xe1, 0x03, 0x22, 0xc9, 0x0c, 0xc2, 0x77, 0xd9,
	0xa0, 0x46, 0x6d, 0x2a, 0xce, 0x21, 0x58, 0x36, 0xa6, 0x8c, 0xbc, 0xd8, 0x4b, 0x99, 0x20, 0xcc,
	0x2f, 0xc1, 0x47, 0x13, 0xf9, 0xa4, 0xf8, 0x68, 0xec, 0x99, 0x8d, 0xda, 0xb7, 0x11, 0x8b, 0x59,
	0x1a, 0x0a, 0xc2, 0xc9, 0x14, 0x60, 0xb6, 0x56, 0xf9, 0xa6, 0x36, 0xba, 0x42, 0x7e, 0x0d, 0xac,
	0x55, 0x9f, 0x14, 0x12, 0x08, 0x0b, 0x0f, 0xb9, 0xfe, 0x59, 0x2e, 0xeb, 0x73, 0x93, 0x1f, 0x0f,
	0xd8, 0xdc, 0x64, 0x56, 0xd7, 0x05, 0x5d, 0x0e, 0x85, 0xaf, 0x0b, 0x7e, 0x0b, 0x43, 0x94, 0xcd,
	0x4a, 0x21, 0xdd, 0x0e, 0x85, 0x63, 0x76, 0x4a, 0xb1, 0x53, 0x2e, 0xc0, 0x42, 0x3b, 0xa5, 0x90,
	0x28, 0xa3, 0x20, 0xf6, 0xd2, 0x0b, 0x41, 0x98, 0x3f, 0xc2, 0xc8, 0xd4, 0xb6, 0x5b, 0x1b, 0x5d,
	0xc5, 0x5e, 0xfa, 0xff, 0xf9, 0x66, 0xd2, 0x2d, 0x61, 0x6e, 0xb2, 0x45, 0x67, 0x88, 0xfe, 0x44,
	0xf2, 0xeb, 0x01, 0x1c, 0x75, 0xfe, 0x00, 0xd0, 0x28, 0x6c, 0xf6, 0x6f, 0xba, 0xd4, 0x48, 0x5f,
	0x34, 0x16, 0x27, 0x8a, 0xf5, 0x4b, 0x5d, 0x4d, 0x65, 0xbe, 0x59, 0x2c, 0x97, 0xae, 0xdb, 0x89,
	0x42, 0xbe, 0xfc, 0xee, 0x7d, 0xe6, 0xfc, 0x83, 0xc2, 0xef, 0xe0, 0x9f, 0x5c, 0xa9, 0x2e, 0x3d,
	0x20, 0xf7, 0xc0, 0x13, 0x09, 0x83, 0xd7, 0x2f, 0x55, 0xe1, 0xd9, 0x3a, 0x5c, 0x6d, 0xff, 0x58,
	0x3b, 0x82, 0x91, 0x44, 0x54, 0x65, 0x8d, 0x34, 0x63, 0x2c, 0x7a, 0xca, 0xef, 0x81, 0x7d, 0x98,
	0xcc, 0x15, 0x87, 0x63, 0x71, 0x61, 0xe5, 0x6c, 0x48, 0xff, 0xc1, 0xcb, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x88, 0x48, 0xaa, 0xf3, 0x2d, 0x02, 0x00, 0x00,
}
